# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a510d914428a889513bc49b7e0cde089aad7eed2d7b99e5d79ccd38bfa072ae56799a015faf2f46546cddbe3a822142f19652d7a52179032f459fce9c800e29a

test:
  secret_key_base: 160e1722edc706704bca53e553aafce1d9bdc021800785a34afc1895f7e6136df910435173d703491609d47e0bef644c822fb138b492699af7c456b56a91fd7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
